"""The DB Agent end to end, against a source database built for the test.

The demo tenants are generated by `scripts.demo_company`, which is the same generator
the product demo uses — so these tests exercise the real path rather than a fixture of
it, and a change that breaks the demo breaks the suite first.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from sqlalchemy import create_engine, event, text
from sqlmodel import Session as OrmSession
from sqlmodel import SQLModel, select

from backend.ingest.database import ConnectionError_, probe, redact
from backend.ingest.loader import to_currency, to_date, to_minor
from backend.ingest.onboarding import Onboarding
from backend.ingest.validate import BalanceSnapshot
from backend.models import Invoice
from scripts import demo_company


@pytest.fixture(scope="module")
def sources(tmp_path_factory: pytest.TempPathFactory) -> dict[str, dict[str, object]]:
    """All four demo tenants, built once."""
    directory = tmp_path_factory.mktemp("demo-sources")
    return {summary["key"]: summary for summary in demo_company.build_all(directory)}


@pytest.fixture
def target(tmp_path: Path) -> OrmSession:
    engine = create_engine(f"sqlite:///{tmp_path / 'target.db'}")
    event.listen(
        engine, "connect", lambda connection, _record: connection.execute("PRAGMA foreign_keys=ON")
    )
    SQLModel.metadata.create_all(engine)
    with OrmSession(engine) as session:
        yield session
    engine.dispose()


TENANTS = ["helios", "lumen", "northgate", "aurora"]


class TestConnect:
    def test_a_password_never_survives_redaction(self) -> None:
        redacted = redact("postgresql+psycopg://treasury:hunter2@db.internal:5432/erp")
        assert "hunter2" not in redacted
        assert "treasury" in redacted and "erp" in redacted

    def test_an_unparseable_url_is_still_safe_to_print(self) -> None:
        assert redact("not a url at all") == "<unparseable url>"

    def test_an_unreachable_source_raises_rather_than_returning_empty(self) -> None:
        with pytest.raises(ConnectionError_):
            probe("postgresql+psycopg://user:pw@127.0.0.1:1/nothing")

    def test_write_capability_is_probed_without_touching_a_tenant_table(
        self, sources: dict[str, dict[str, object]]
    ) -> None:
        url = str(sources["helios"]["url"])
        before = _row_count(url, "ar_open_items")
        result = probe(url)
        assert result.can_write is True
        assert _row_count(url, "ar_open_items") == before


class TestConversion:
    def test_major_units_are_parsed_by_digit_splitting(self) -> None:
        assert to_minor("1234.56", "USD", "major") == 123_456
        assert to_minor("-0.07", "USD", "major") == -7

    def test_minor_units_pass_through_as_integers(self) -> None:
        assert to_minor(123_456, "USD", "minor") == 123_456

    def test_an_unsupported_currency_is_refused_not_defaulted(self) -> None:
        with pytest.raises(ValueError, match="ISO-4217"):
            to_currency("XYZ", "USD")

    def test_a_blank_currency_falls_back_to_the_tenant_default(self) -> None:
        assert to_currency(None, "EUR") == "EUR"

    def test_a_timestamp_is_narrowed_to_its_date(self) -> None:
        assert to_date("2026-03-02T14:31:00Z").isoformat() == "2026-03-02"


class TestOnboarding:
    @pytest.mark.parametrize("key", TENANTS)
    def test_every_demo_schema_maps_to_all_six_entities(
        self, key: str, sources: dict[str, dict[str, object]]
    ) -> None:
        onboarding = _prepared(sources[key])
        assert onboarding.mapping is not None
        assert set(onboarding.mapping.entities) == {
            "BankAccount",
            "BankTransaction",
            "Customer",
            "Invoice",
            "Vendor",
            "VendorInvoice",
        }

    @pytest.mark.parametrize("key", TENANTS)
    def test_the_only_residue_is_the_tenants_own_control_table(
        self, key: str, sources: dict[str, dict[str, object]]
    ) -> None:
        onboarding = _prepared(sources[key])
        assert onboarding.residue is not None
        assert len(onboarding.residue.tables) == 1
        assert "control" in onboarding.residue.tables[0].lower()
        assert onboarding.residue.columns == ()

    def test_the_lexicon_resolves_the_demo_schemas_without_a_model_call(
        self, sources: dict[str, dict[str, object]]
    ) -> None:
        assert _prepared(sources["northgate"]).model_calls == 0

    @pytest.mark.parametrize("key", TENANTS)
    def test_a_load_ties_out_to_the_tenants_own_control_totals(
        self, key: str, sources: dict[str, dict[str, object]], target: OrmSession, tmp_path: Path
    ) -> None:
        summary = sources[key]
        onboarding = _prepared(summary)
        report = onboarding.load(target, stated=_stated(summary), mapping_dir=tmp_path / "mappings")

        assert onboarding.reconciliation is not None
        assert onboarding.reconciliation.accepted, onboarding.reconciliation.failures
        assert report.rejects == []
        assert onboarding.mapping_path is not None and onboarding.mapping_path.exists()

    def test_a_wrong_control_total_rejects_the_mapping_and_says_why(
        self, sources: dict[str, dict[str, object]], target: OrmSession, tmp_path: Path
    ) -> None:
        """The gate that makes a proposed mapping safe: wrong mappings fail arithmetically."""
        summary = sources["helios"]
        onboarding = _prepared(summary)
        stated = _stated(summary)
        onboarding.load(
            target,
            stated=BalanceSnapshot(
                ar_minor=stated.ar_minor + 100_00,
                ap_minor=stated.ap_minor,
                cash_minor=stated.cash_minor,
            ),
            mapping_dir=tmp_path / "mappings",
        )
        assert onboarding.reconciliation is not None
        assert onboarding.reconciliation.accepted is False
        assert any("AR mismatch" in failure for failure in onboarding.reconciliation.failures)
        # Nothing is frozen on a failed reconciliation: an unverified mapping is not a
        # mapping the runtime should ever be able to pick up.
        assert onboarding.mapping_path is None

    def test_loading_twice_updates_rows_rather_than_doubling_the_ledger(
        self, sources: dict[str, dict[str, object]], target: OrmSession, tmp_path: Path
    ) -> None:
        summary = sources["lumen"]
        onboarding = _prepared(summary)
        first = onboarding.load(target, stated=_stated(summary), mapping_dir=tmp_path / "m1")
        target.commit()
        second = onboarding.load(target, stated=_stated(summary), mapping_dir=tmp_path / "m2")
        target.commit()

        assert first.counts == second.counts
        held = target.exec(select(Invoice).where(Invoice.tenant_id == "lumen")).all()
        assert len(held) == first.counts["Invoice"]

    def test_minor_unit_and_major_unit_sources_agree_on_what_a_cent_is(
        self, sources: dict[str, dict[str, object]], target: OrmSession, tmp_path: Path
    ) -> None:
        """Northgate stores integer cents; the others store decimals. Both must reconcile,
        which is only possible if the unit finding was read correctly for each."""
        for key in ("northgate", "helios"):
            summary = sources[key]
            onboarding = _prepared(summary)
            onboarding.load(target, stated=_stated(summary), mapping_dir=tmp_path / key)
            assert onboarding.reconciliation is not None
            assert onboarding.reconciliation.accepted

    def test_drift_holds_ingestion_when_the_source_schema_changes(
        self, sources: dict[str, dict[str, object]], target: OrmSession, tmp_path: Path
    ) -> None:
        summary = sources["aurora"]
        onboarding = _prepared(summary)
        onboarding.load(target, stated=_stated(summary), mapping_dir=tmp_path / "mappings")
        assert onboarding.check_drift().changed is False

        engine = create_engine(str(summary["url"]))
        with engine.begin() as connection:
            connection.exec_driver_sql(
                'ALTER TABLE "openReceivables" ADD COLUMN "taxCode" VARCHAR(8)'
            )
        engine.dispose()

        report = onboarding.check_drift()
        assert report.changed is True
        assert report.hold_ingestion is True


class TestStageGates:
    def test_introspecting_before_connecting_is_refused_by_name(self) -> None:
        onboarding = Onboarding(tenant_id="t", company_name="T")
        with pytest.raises(RuntimeError, match="connect"):
            onboarding.introspect()

    def test_a_forgotten_credential_cannot_be_used_for_a_load(
        self, sources: dict[str, dict[str, object]], target: OrmSession
    ) -> None:
        onboarding = _prepared(sources["helios"])
        onboarding.forget()
        with pytest.raises(RuntimeError, match="no longer held"):
            onboarding.load(target, stated=_stated(sources["helios"]))


def _prepared(summary: dict[str, object]) -> Onboarding:
    onboarding = Onboarding(
        tenant_id=str(summary["key"]),
        company_name=str(summary["company"]),
        default_currency=str(summary["currency"]),
    )
    onboarding.connect(str(summary["url"]))
    onboarding.introspect()
    onboarding.classify()
    onboarding.draft()
    return onboarding


def _stated(summary: dict[str, object]) -> BalanceSnapshot:
    controls = summary["control_balances"]
    assert isinstance(controls, dict)
    return BalanceSnapshot(
        ar_minor=controls["ar_control_minor"],
        ap_minor=controls["ap_control_minor"],
        cash_minor=controls["cash_control_minor"],
        currency=controls["currency"],
    )


def _row_count(url: str, table: str) -> int:
    engine = create_engine(url)
    try:
        with engine.connect() as connection:
            return int(connection.execute(text(f'SELECT count(*) FROM "{table}"')).scalar() or 0)
    finally:
        engine.dispose()
