/**
 * Typed views over the recorded golden path.
 *
 * The JSON beside this file is generated by `python -m scripts.export_frontend_fixtures`
 * and is the real output of running Monday end to end -- the real event ordering, the
 * conflict that actually fired, the bundle that actually failed stress. This module only
 * puts types on it.
 *
 * The casts are deliberate and narrow. `tsc` cannot know that a JSON string literal is
 * the `AgentRole` union, and widening the contracts to `string` to avoid a cast would
 * lose the exhaustiveness checking that makes `project()` safe to extend. What guards the
 * cast is not TypeScript: it is `tests/unit/test_frontend_fixture_parity.py`, which
 * regenerates the file from the Python contracts and fails the build on any drift.
 */

import type {
  ApprovalRequest,
  Evidence,
  Recommendation,
  Strategy,
  WorklistItem,
} from "@/lib/contracts";
import type { WarRoomEvent } from "@/lib/events";

import approvals from "./approvals.json";
import recommendation from "./recommendation.json";
import warRoom from "./war-room.json";

export interface WarRoomFixture {
  events: WarRoomEvent[];
  investigationId: string;
  planId: string;
  planRationale: string;
}

export const warRoomFixture: WarRoomFixture = {
  events: warRoom.events as unknown as WarRoomEvent[],
  investigationId: warRoom.investigation.investigation_id,
  planId: warRoom.investigation.plan_id,
  planRationale: warRoom.investigation.plan_rationale,
};

/** One objective's contribution to a bundle's score, and the sentence behind the number. */
export interface ObjectiveScore {
  objective: string;
  score: string;
  weight: number;
  basis: string;
}

export interface ScoreCard {
  strategy_id: string;
  total: string;
  objectives: ObjectiveScore[];
  unscored: string[];
}

export interface RecommendationFixture {
  recommendation: Recommendation;
  strategies: Strategy[];
  scores: Record<string, ScoreCard>;
}

export const recommendationFixture: RecommendationFixture = {
  recommendation: recommendation.recommendation as unknown as Recommendation,
  strategies: recommendation.strategies as unknown as Strategy[],
  scores: recommendation.scores as unknown as Record<string, ScoreCard>,
};

/** The classification and the sentence behind it. Both are rendered on the card. */
export interface RiskVerdict {
  risk: "auto_safe" | "requires_approval" | "blocked";
  reversibility: string;
  magnitude: string;
  counterparty_impact: string;
  basis: string;
}

export interface ApprovalCardFixture {
  request: ApprovalRequest & { route?: ApprovalRoute | null };
  /** Pre-rendered by the backend in the frozen field order. The UI must not reorder it. */
  card: Record<string, string>;
  verdict: RiskVerdict | null;
  state: "draft" | "pending" | "approved" | "rejected" | "blocked" | "expired";
}

export interface ApprovalRoute {
  route_id: string;
  action_class: string;
  responsible: string;
  reviewer?: string | null;
  accountable?: string | null;
  informed: string[];
  blocked: boolean;
  blocked_reason?: string | null;
}

export interface RejectedActionFixture {
  action: {
    kind: string;
    rationale: string;
    counterparty?: string | null;
    document_ref?: string | null;
    amount?: { minor_units: number; currency: string } | null;
    delay_days?: number | null;
  };
  rejected_by: string;
  reason: string;
  evidence: Evidence[];
}

export interface ApprovalsFixture {
  fieldOrder: string[];
  worklist: WorklistItem[];
  cards: ApprovalCardFixture[];
  rejected: RejectedActionFixture[];
}

export const approvalsFixture: ApprovalsFixture = {
  fieldOrder: approvals.field_order,
  worklist: approvals.worklist as unknown as WorklistItem[],
  cards: approvals.cards as unknown as ApprovalCardFixture[],
  rejected: approvals.rejected as unknown as RejectedActionFixture[],
};
