"""Record the golden path and hand it to the frontend as JSON.

    python -m scripts.export_frontend_fixtures

The War Room, Recommendation and Approvals screens are built against fixtures, like the
Forecast screen before them. The difference is where the fixtures come from: these are not
written by hand, they are the actual output of running Monday end to end against the
recorded toolset and the replay provider.

That matters more than it sounds. A hand-written war-room fixture is a designer's idea of
what an investigation looks like, and it will quietly diverge from what the orchestrator
emits -- usually in the direction of being tidier, because nobody hand-writes the agent
that timed out or the bundle that failed stress. Generating it means the screen is built
against the real event ordering, the real replan history and the real refusals, including
the ugly parts. `tests/unit/test_frontend_fixture_parity.py` fails the build if the two
sides drift.

The script goes through the same `Session` the API does, so it records whatever the
engine actually returns rather than a separately-maintained idea of it.
"""

from __future__ import annotations

import asyncio
import json
from pathlib import Path
from typing import Any

from fastapi.encoders import jsonable_encoder

from backend.api.approvals import ApprovalBoard, ApprovalCard
from backend.api.session import Session
from backend.contracts.approvals import ApprovalRole

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "frontend" / "src" / "fixtures"

TREASURER = "treasurer@novatech"

BANNER = "GENERATED by scripts/export_frontend_fixtures.py -- do not edit. Parity is in CI."


async def record() -> dict[str, Any]:
    """Run Monday, breach the floor, investigate, and prepare the cards."""
    session = Session()

    cycle = await session.run_cycle()
    session.publish(published_by=TREASURER, published_by_role=ApprovalRole.TREASURER)
    check = await session.check_policy()
    if not check.escalate:
        raise SystemExit(
            "the seeded Monday no longer breaches policy, so there is no war room to "
            "record. Either the fixtures moved or the floor did; both are worth knowing."
        )

    investigation = await session.open_war_room()
    pack = await session.approval_pack()

    board = ApprovalBoard(
        worklist=pack.worklist,
        cards=[
            ApprovalCard(
                request=request,
                card=request.card(),
                verdict=pack.verdicts.get(request.worklist_seq or -1),
                state=session.state_of(request.request_id),
            )
            for request in pack.requests
        ],
        rejected=pack.blocked,
    )

    return {
        "war-room": {
            "_banner": BANNER,
            # `runs` is carried once, at the top level; the nested copy is the same rows.
            "investigation": investigation.model_dump(mode="python", exclude={"runs"}),
            # The whole stream, cycle steps included: the War Room screen replays it from
            # seq 0 exactly as a late-joining browser would.
            "events": session.bus.history(),
            "runs": session.runs.all(investigation_id=investigation.investigation_id),
        },
        "recommendation": {
            "_banner": BANNER,
            "recommendation": investigation.recommendation,
            "scores": investigation.scores,
            "strategies": investigation.strategies,
        },
        "approvals": {"_banner": BANNER, **board.model_dump(mode="python")},
        "cycle": {"_banner": BANNER, "cycle": cycle, "policy": check},
    }


# Anything the run does not decide: a uuid, a wall clock, a measured latency. Left alone
# these change on every regeneration, so the committed file churns and the parity check
# degrades into "did someone run the script recently", which catches nothing.
_TIMESTAMPS = frozenset(
    {
        "ts",
        "at",
        "created_at",
        "decided_at",
        "started_at",
        "ended_at",
        "published_at",
        "detected_at",
        "retrieved_at",
    }
)
_DURATIONS = frozenset({"elapsed_ms", "latency_ms", "duration_ms", "queued_ms"})
# Field name -> the kind it names. `approval_request_id` on a worklist row and
# `request_id` on the card are the same uuid, so they must intern to the same label --
# a screen that showed a row pointing at `approval_request-2` and a card called
# `request-1` would have broken the only link between them.
_INTERNED: dict[str, str] = {
    "event_id": "event",
    "investigation_id": "investigation",
    "run_id": "run",
    "request_id": "request",
    "approval_request_id": "request",
    "override_id": "override",
    "recommendation_id": "recommendation",
    "conflict_id": "conflict",
}

# The context pack is the brief an agent was opened with, not its reasoning -- but it is
# still a prompt, it is most of the file's weight, and no screen renders it. The rule the
# War Room stream keeps is easier to keep if the prompt is not sitting in the bundle.
_DROPPED = frozenset({"context_pack"})

FROZEN_TS = "2026-03-02T09:00:00Z"


def _canonicalise(node: Any, ids: dict[str, str]) -> Any:
    """Replace what the run did not decide with something stable and readable.

    Ids are interned per kind and numbered in first-seen order, so `run-3` is the third
    agent run the stream mentions rather than the third uuid the traversal happened to
    reach. The screens show these, and a reader should be able to follow them.
    """
    if isinstance(node, dict):
        out: dict[str, Any] = {}
        for key, value in node.items():
            if key in _DROPPED:
                continue
            if key in _TIMESTAMPS and isinstance(value, str):
                out[key] = FROZEN_TS
            elif key in _DURATIONS and isinstance(value, int):
                # A measured latency is real but not reproducible. Zero says "this run was
                # recorded", where a plausible-looking 3ms would say "this run took 3ms".
                out[key] = 0
            elif key in _INTERNED and isinstance(value, str):
                kind = _INTERNED[key]
                seen = sum(1 for name in ids.values() if name.startswith(f"{kind}-"))
                out[key] = ids.setdefault(value, f"{kind}-{seen + 1}")
            else:
                out[key] = _canonicalise(value, ids)
        return out
    if isinstance(node, list):
        return [_canonicalise(item, ids) for item in node]
    return node


def _stable(payload: Any) -> str:
    """Deterministic bytes: same golden path, same file, so parity is a diff not a guess."""
    canonical = _canonicalise(jsonable_encoder(payload), {})
    return json.dumps(canonical, indent=2, sort_keys=True) + "\n"


async def main() -> None:
    recorded = await record()
    TARGET.mkdir(parents=True, exist_ok=True)
    for name, payload in recorded.items():
        path = TARGET / f"{name}.json"
        path.write_text(_stable(payload), encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    asyncio.run(main())
